### ISSUE TITLE
有关签到

### ISSUE THREAD

**Issue by adwwee** [JustUndertaker/mini_jx3_bot#1]
请问一下签到功能的总金币数额是否能读取，我想在使用其他插件时用这个金币来实现功能，但是我找了半天也没看到这个签到功能的记录存放在那个文件下，请大佬执教一下

**Comment by JustUndertaker** [comment]
> 请问一下签到功能的总金币数额是否能读取，我想在使用其他插件时用这个金币来实现功能，但是我找了半天也没看到这个签到功能的记录存放在那个文件下，请大佬执教一下

目前代码没有相关功能，你可以自己实现一个接口：
[src/modules/user_info.py](https://github.com/JustUndertaker/mini_jx3_bot/blob/c96a8ce53f824deabb158c7d8c103d2d4f0c86ae/src/modules/user_info.py)
```python
@classmethod
    async def get_user_gold(cls, user_id: int, group_id: int) -> int:
        '''获取用户金币'''
        record, _ = await UserInfo.get_or_create(user_id=user_id, group_id=group_id)
        return record.gold
```

**Comment by adwwee** [comment]
感谢指点，谢谢
