### ISSUE TITLE
用golang重写现实吗

### ISSUE THREAD

**Issue by passerbyo** [JustUndertaker/mini_jx3_bot#13]

**Comment by JustUndertaker** [comment]
gocq提供了一个无头协议端用于收发消息，所以用什么语言重写不是问题，主要看哪个方便。python这边有nb1，nb2；js有koishi；java也有相关框架；我使用nb2只是个人选择，golang那边我不熟，如果有相关框架也可以试试，或者直接不用框架，自己实现消息收发和管理也行。
