### ISSUE TITLE
jx3api部分接口更新

### ISSUE THREAD

**Issue by byscut** [JustUndertaker/mini_jx3_bot#3]
今天发现日常模块返回数据结构更新了：
{
  "code": 200,
  "msg": "success",
  "data": {
    "date": "2022-03-01",
    "week": "二",
    "war": "英雄武氏别院",
    "battle": "三国古战场",
    "public": "藏剑·乱世",
    "camp": "藏剑·乱世",
    "team": [
      "洛阳城·攻打应天门;洛阳·神兵迷踪",
      "英雄空雾峰;英雄寂灭厅;英雄一线天",
      "雷域大泽;范阳夜变;战宝迦兰"
    ]
  },
  "time": 1646122697
}

**Comment by JustUndertaker** [comment]
> 今天发现日常模块返回数据结构更新了： { "code": 200, "msg": "success", "data": { "date": "2022-03-01", "week": "二", "war": "英雄武氏别院", "battle": "三国古战场", "public": "藏剑·乱世", "camp": "藏剑·乱世", "team": [ "洛阳城·攻打应天门;洛阳·神兵迷踪", "英雄空雾峰;英雄寂灭厅;英雄一线天", "雷域大泽;范阳夜变;战宝迦兰" ] }, "time": 1646122697 }

jx3api目前已经更新了数据，部分接口有变化，目前正在dev分支中适配，还没有做完（在鸽中。目前临时解决方案是将
https://github.com/JustUndertaker/mini_jx3_bot/blob/c96a8ce53f824deabb158c7d8c103d2d4f0c86ae/config.yml#L10
改为：
```yml
jx3_url: https://api.jx3api.com
```
后续等待适配吧。

**Comment by byscut** [comment]
辛苦大佬😊
